import test from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {randomUUID} from "node:crypto";
import {ControlPlaneDatabase} from "../src/db.js";
import {loadConfig} from "../src/config.js";
import {ClaudePreferencesService} from "../src/claude-preferences.js";
import type {Principal} from "../src/auth.js";
test("Claude settings persist after reopening, isolate sessions and reject stale or unsupported writes",t=>{
 const dir=mkdtempSync(join(tmpdir(),"claude-prefs-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const path=join(dir,"db.sqlite");let db=new ControlPlaneDatabase(path);t.after(()=>db.close());
 const cfg=loadConfig({AUTH_MODE:"password",ADMIN_EMAIL:"prefs@example.test",ADMIN_PASSWORD:randomUUID(),DATABASE_PATH:path,PUBLIC_ORIGIN:"http://test",COOKIE_SECURE:"false"});
 const {workspaceId}=db.bootstrap(cfg);const at=new Date().toISOString();
 const user=db.get<{user_id:string}>("SELECT user_id FROM users LIMIT 1")!;
 const principal={workspaceId,userId:user.user_id} as Principal;
 db.run(`INSERT INTO machines(machine_id,workspace_id,public_key_spki,public_key_fingerprint,name,platform,platform_release,architecture,agent_version,identity_state,security_state,reachability,compatibility,capacity,created_at,updated_at,discovery_json) VALUES('m',?,'key','fingerprint','host','linux','24','x64','0.30.59','active','normal','online','compatible','idle',?,?,?)`,workspaceId,at,at,JSON.stringify({agentRuntimes:{claude:{models:[{model:"claude-sonnet-5-5",displayName:"Sonnet 5.5",efforts:["high"],supportsAutoMode:true}],permissionModes:["default","auto","acceptEdits","dontAsk"]}}}));
 db.run(`INSERT INTO projects(project_id,workspace_id,machine_id,external_id,alias,canonical_root,identity_hash,provider,created_at,last_reported_at) VALUES('p',?,'m','p','project','/work','hash','claude',?,?)`,workspaceId,at,at);
 for(const id of ["s1","s2"])db.run(`INSERT INTO logical_sessions(logical_session_id,workspace_id,machine_id,project_id,title,managed,execution_state,reachability,created_at,updated_at) VALUES(?,?,'m','p','session',1,'idle','live',?,?)`,id,workspaceId,at,at);
 let service=new ClaudePreferencesService(db);assert.deepEqual(service.read(principal,"s1"),{settings:null,revision:0});
 const settings={model:"claude-sonnet-5-5",effort:"high",permissionMode:"auto",mode:"plan"};
 assert.deepEqual(service.write(principal,"s1",{settings,revision:0}),{settings,revision:1});
 assert.throws(()=>service.write(principal,"s1",{settings,revision:0}),/changed in another browser/);
 assert.throws(()=>service.write(principal,"s1",{settings:{...settings,permissionMode:"bypassPermissions"},revision:1}),/Unsupported/);
 assert.throws(()=>service.write(principal,"s1",{settings:{...settings,model:"claude-fake-9"},revision:1}),/native host catalog/);
 assert.throws(()=>service.read({...principal,workspaceId:"other"},"s1"),/not found/);
 assert.deepEqual(service.read(principal,"s2"),{settings:null,revision:0});
 db.close();db=new ControlPlaneDatabase(path);service=new ClaudePreferencesService(db);
 assert.deepEqual(service.read(principal,"s1"),{settings,revision:1});
 db.run("UPDATE projects SET provider='codex' WHERE project_id='p'");assert.throws(()=>service.write(principal,"s1",{settings,revision:1}),/Claude Code session/);
});
