import { DatabaseSync } from 'node:sqlite';
import type { ControlPlaneDatabase } from '../src/db.js';
import type { Principal } from '../src/auth.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, symlink, rm, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { deliveryPlan, DELIVERY_COPY, deliveredPath } from '../src/file-delivery.js';
const base={path:'/outside/report.pdf',root:'/project',platform:'darwin',provider:'codex',sessionId:'session',userId:'owner',mutationId:'mutation-1'};
test('delivery preserves exact arguments and isolates session/user/retry identity',()=>{
 const p=deliveryPlan(base);
 assert.deepEqual(deliveryPlan(base),p);
 assert.notEqual(deliveryPlan({...base,userId:'other'}).path,p.path);
 assert.notEqual(deliveryPlan({...base,sessionId:'other'}).path,p.path);
 assert.ok(DELIVERY_COPY.length<2000);
 assert.equal(deliveryPlan({...base,path:'/outside/a $(touch bad).pdf'}).argv[3],'/outside/a $(touch bad).pdf');
 for(const path of ['/outside/.env','/outside/.ssh/key.pdf','/outside/auth.json','relative.pdf','/outside/run.sh'])assert.throws(()=>deliveryPlan({...base,path}));
 assert.throws(()=>deliveryPlan({...base,platform:'win32'}));
 assert.throws(()=>deliveryPlan({...base,provider:'claude'}));
});
test('real copy retains source, preserves bytes, refuses overwrite and symlink escape',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'delivery-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));
 const root=join(dir,'project');await mkdir(root);
 const source=join(dir,'report.pdf'),data=Buffer.alloc(400_000,37);await writeFile(source,data);
 const plan=deliveryPlan({...base,root,path:source,platform:'linux'});
 const run=()=>spawnSync(plan.argv[0]!,plan.argv.slice(1),{encoding:'utf8'});
 assert.equal(run().status,0);
 assert.deepEqual(await readFile(plan.path),data);assert.deepEqual(await readFile(source),data);
 assert.notEqual(run().status,0);assert.deepEqual(await readFile(plan.path),data);
 const link=join(dir,'linked.pdf');await symlink(source,link);
 const linked=deliveryPlan({...base,root,path:link,mutationId:'linked'});
 assert.notEqual(spawnSync(linked.argv[0]!,linked.argv.slice(1)).status,0);
 assert.equal((await readdir(root)).length,1);
});

test('old-link lookup never crosses user/workspace/session and excludes failed or expired copies',()=>{
 const sqlite=new DatabaseSync(':memory:');
 sqlite.exec(`CREATE TABLE commands(command_id,workspace_id,actor_user_id,logical_session_id,type,created_at);
 CREATE TABLE command_contents(command_id,body_json,deleted_at);
 CREATE TABLE command_projection(command_id,state);`);
 const p=deliveryPlan(base);
 sqlite.prepare('INSERT INTO commands VALUES(?,?,?,?,?,?)').run('copy','workspace','owner','session','codex.manage','2026-01-01');
 sqlite.prepare('INSERT INTO command_contents VALUES(?,?,NULL)').run('copy',JSON.stringify({operation:'terminal.run',arguments:{argv:p.argv}}));
 sqlite.prepare('INSERT INTO command_projection VALUES(?,?)').run('copy','applied');
 const db={all:(sql:string,...args:any[])=>sqlite.prepare(sql).all(...args)} as unknown as ControlPlaneDatabase;
 const owner={workspaceId:'workspace',userId:'owner'} as Principal;
 const success=()=>({result:{codexResult:{status:'completed'}}});
 assert.equal(deliveredPath(db,owner,'session',base.path,success),p.path);
 assert.equal(deliveredPath(db,{...owner,userId:'other'},'session',base.path,success),undefined);
 assert.equal(deliveredPath(db,{...owner,workspaceId:'other'},'session',base.path,success),undefined);
 assert.equal(deliveredPath(db,owner,'other',base.path,success),undefined);
 assert.equal(deliveredPath(db,owner,'session','/other.pdf',success),undefined);
 assert.equal(deliveredPath(db,owner,'session',base.path,()=>({result:{codexResult:{status:'partialFailure'}}})),undefined);
 sqlite.exec("UPDATE command_contents SET deleted_at='expired'");
 assert.equal(deliveredPath(db,owner,'session',base.path,success),undefined);
 sqlite.close();
});
