import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import type { ControlPlaneDatabase } from "../src/db.js";
import type { CoordinationService } from "../src/coordination.js";
import type { Principal } from "../src/auth.js";
import { editQueuedPrompt } from "../src/queue-edit.js";
test("queue edit replaces an immutable command atomically, preserves order, fences races and retries",t=>{
 const sql=new DatabaseSync(":memory:");t.after(()=>sql.close());const expiry=new Date(Date.now()+600000).toISOString();
 sql.exec(`CREATE TABLE logical_sessions(logical_session_id TEXT,workspace_id TEXT,queue_version INTEGER,project_id TEXT,thread_control_version INTEGER,active_turn_id TEXT);
 CREATE TABLE projects(project_id TEXT,lease_version INTEGER); CREATE TABLE execution_segments(logical_session_id TEXT,execution_segment_id TEXT,ended_at TEXT);
 CREATE TABLE turn_queue(queue_item_id TEXT PRIMARY KEY,logical_session_id TEXT,workspace_id TEXT,command_id TEXT,position INTEGER,state TEXT,expires_at TEXT,updated_at TEXT,UNIQUE(logical_session_id,position));
 CREATE TABLE command_projection(command_id TEXT,state TEXT,updated_at TEXT); CREATE TABLE command_lifecycle(command_id TEXT,state TEXT,detail_json TEXT,created_at TEXT);
 INSERT INTO logical_sessions VALUES('s','w',3,'p',2,NULL); INSERT INTO projects VALUES('p',1); INSERT INTO execution_segments VALUES('s','seg',NULL);
 INSERT INTO command_projection VALUES('old','queued','');`);
 sql.prepare("INSERT INTO turn_queue VALUES('q','s','w','old',1,'queued',?,'')").run(expiry);
 sql.prepare("INSERT INTO turn_queue VALUES('q2','s','w','other',2,'queued',?,'')").run(expiry);
 const db={get:(s:string,...a:(string|number)[])=>sql.prepare(s).get(...a),run:(s:string,...a:(string|number)[])=>sql.prepare(s).run(...a),audit:()=>{},transaction:(fn:()=>unknown)=>{sql.exec('BEGIN');try{const out=fn();sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}} as unknown as ControlPlaneDatabase;
 const original={prompt:"old",images:["data:image/png;base64,abc"],permissionProfile:"project",settings:{model:"m",mode:"default"}};let saved:Record<string,unknown>|undefined;let fail=false;
 const coordination={getCommand:(_p:unknown,id:string)=>({payload:id==='old'?original:saved}),createCommand:(_p:unknown,_s:string,input:{payload:Record<string,unknown>},within:boolean)=>{assert.equal(within,true);assert.equal(input.payload.permissionProfile,undefined);if(fail)throw new Error('validation failed');saved=input.payload;sql.prepare("INSERT INTO turn_queue VALUES('newq','s','w','new',3,'queued',?,'')").run(expiry);sql.exec("UPDATE logical_sessions SET queue_version=queue_version+1");return {command:{commandId:'new'},duplicate:false};}} as unknown as CoordinationService;
 const principal={workspaceId:'w',userId:'u',clientSessionId:'c'} as Principal;const input={prompt:'edited',queueVersion:3,clientMutationId:'mutation-1'};
 assert.throws(()=>editQueuedPrompt(db,coordination,{...principal,workspaceId:'other'},'s','q',input),/not found/);
 assert.throws(()=>editQueuedPrompt(db,coordination,principal,'s','q',{...input,queueVersion:2}),/变化/);
 fail=true;assert.throws(()=>editQueuedPrompt(db,coordination,principal,'s','q',input),/validation/);assert.equal(sql.prepare("SELECT state FROM turn_queue WHERE queue_item_id='q'").get()?.state,'queued');fail=false;
 assert.deepEqual(editQueuedPrompt(db,coordination,principal,'s','q',input),{commandId:'new',duplicate:false});assert.deepEqual(saved?.images,original.images);assert.equal(original.prompt,'old');
 assert.deepEqual(sql.prepare("SELECT queue_item_id FROM turn_queue WHERE state='queued' ORDER BY position").all().map(r=>r.queue_item_id),['newq','q2']);
 assert.deepEqual(editQueuedPrompt(db,coordination,principal,'s','q',input),{commandId:'new',duplicate:true});
 assert.throws(()=>editQueuedPrompt(db,coordination,principal,'s','q',{...input,prompt:'changed'}),/changed/);
});
