import assert from "node:assert/strict";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { buildControlPlane } from "../src/server.js";
import { loadConfig } from "../src/config.js";
import { channelControl } from "../src/runtime-channel.js";
test("runtime channel controls require login and CSRF; absent targets never become a forced upgrade", async t => {
  const directory = await mkdtemp(join(tmpdir(), "runtime-channel-api-"));
  const config = loadConfig({ ADMIN_EMAIL: "runtime@example.test", ADMIN_PASSWORD: "runtime-channel-test-password", PUBLIC_ORIGIN: "http://runtime.test", COOKIE_SECURE: "false", DATABASE_PATH: join(directory, "test.sqlite"), RUNTIME_RELEASE_DIR: join(directory, "channel"), LOG_LEVEL: "silent" });
  const { app } = await buildControlPlane(config);
  t.after(async () => { await app.close(); await rm(directory, { recursive: true, force: true }); });
  assert.equal((await app.inject({ method: "GET", url: "/api/runtime-release" })).statusCode, 401);
  assert.deepEqual((await app.inject({ method: "GET", url: "/api/runtime-release/target" })).json(), { target: null });
  const login = await app.inject({ method: "POST", url: "/api/auth/login", headers: { origin: config.publicOrigin }, payload: { email: config.adminEmail, password: config.adminPassword } });
  const cookie = String(login.headers["set-cookie"]).split(";")[0]!;
  const base = { method: "POST" as const, url: "/api/runtime-release/control", payload: { action: "pause" } };
  assert.equal((await app.inject({ ...base, headers: { origin: config.publicOrigin, cookie } })).statusCode, 403);
  const headers = { origin: config.publicOrigin, cookie, "x-csrf-token": login.json().csrfToken };
  assert.equal((await app.inject({ ...base, headers })).statusCode, 200);
  assert.equal(channelControl(config.runtimeReleaseDir!).paused, true);
  assert.equal((await app.inject({ ...base, headers, payload: { action: "check" } })).statusCode, 409);
  assert.equal((await app.inject({ ...base, headers, payload: { action: "rollback" } })).statusCode, 409);
  assert.equal((await app.inject({ ...base, headers, payload: { action: "resume" } })).statusCode, 200);
  assert.equal(channelControl(config.runtimeReleaseDir!).paused, false);
  assert.equal((await app.inject({ method: "GET", url: "/downloads/managed-codex/control.json" })).statusCode, 404);
  const artifact = "codex-code-mode-host-darwin-arm64-0.154.0-0123456789abcdef";
  await mkdir(join(config.runtimeReleaseDir!, "public"), { recursive: true });
  await writeFile(join(config.runtimeReleaseDir!, "public", artifact), "0123456789");
  const full = await app.inject({ method: "GET", url: `/downloads/managed-codex/${artifact}` });
  assert.equal(full.statusCode, 200); assert.equal(full.headers["accept-ranges"], "bytes"); assert.equal(full.body, "0123456789");
  const partial = await app.inject({ method: "GET", url: `/downloads/managed-codex/${artifact}`, headers: { range: "bytes=4-7" } });
  assert.equal(partial.statusCode, 206); assert.equal(partial.headers["content-range"], "bytes 4-7/10"); assert.equal(partial.body, "4567");
  const invalid = await app.inject({ method: "GET", url: `/downloads/managed-codex/${artifact}`, headers: { range: "bytes=10-" } });
  assert.equal(invalid.statusCode, 416); assert.equal(invalid.headers["content-range"], "bytes */10");
});
